env:
  node: true
  es2020: true
  jest: true

extends:
  - "airbnb-base"

parserOptions:
  sourceType: module
  ecmaVersion: 2020

rules:
  no-console: 0
  import/extensions: 0
  import/prefer-default-export: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
